# Generated by Django 3.2.13 on 2022-04-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
    ]
